front/package.json
front/src/app/login/page.tsx
front/src/components/AuthenticationForm.tsx
front/src/components/LoginForm.tsx
front/src/components/SignUpPrompt.tsx
front/src/components/SocialLogin.tsx
front/src/components/WelcomeMessage.tsx
front/yarn.lock

- 로그인 양식 radius 크기 추가 수정
- OAuth 추후 수정할 부분 TOOD 주석
- Unique key 수정
- React hook form
- zod
- @hookform/resolvers
- axios
- Zod를 사용한 이메일 및 비밀번호 유효성 검사
- axios로 로그인 API 호출 처리
- 입력값 오류 메시지 및 제출 중 로딩 상태 반영
- LABEL_CLASS 추가
- 컴포넌트 밑으로 전역변수 내림
- 텍스트와 링크 경로를 title 변수를 사용해 간결하게 처리

Feature: 로그인 이메일, 비밀번호 유효성 검사

---

front/package.json
front/src/components/LoginForm.test.tsx
front/src/components/LoginForm.tsx
front/vitest.config.ts
front/yarn.lock

- Vitest 설정 파일(vitest.config.ts)에서 테스트 환경을 jsdom으로 변경
- React 플러그인 추가
- 테스트 관련 라이브러리 설치:
- @testing-library/dom
- @testing-library/react
- jsdom

Chore: 테스트 환경 설정 수정

---

back/src/main/java/back/api/user/UserController.java
back/src/main/java/back/api/user/token/TokenController.java
back/src/main/java/back/api/user/token/dto/TokenResponse.java
back/src/main/java/back/common/config/CorsConfig.java
back/src/main/java/back/common/filter/JwtAuthenticationFilter.java
back/src/main/java/back/common/util/CookieUtil.java
back/src/main/java/back/domain/user/dto/UserResponse.java

- response body에서 access token,refresh token 값을 넘기는 거에 대한 보안 이슈 생각
- refresh token 쿠키 값으로 넘김(http only)

refactor: login api

---

front/src/app/gatherings/components/Button.tsx
front/src/app/gatherings/components/Gatherings.tsx
front/src/app/gatherings/create/components/Category.tsx
front/src/app/gatherings/create/components/Connection.tsx
front/src/app/gatherings/create/components/Dropdown.tsx
front/src/app/gatherings/create/components/GatheringForm.tsx
front/src/app/gatherings/create/components/ImageUploader.tsx
front/src/app/gatherings/create/page.tsx
front/src/store/gatherings/useFormStore.ts
front/src/types/options.ts

- 기본 레이아웃 구현
- 드롭다운, 카테고리, 진행방법(Connection), 이미지 업로더 컴포넌트 구현
- useFormStore를 활용해 데이터 상태 관리 로직 구현

Feat: 모임 만들기 페이지 구현

---

front/public/images/caret-down.svg
front/src/app/gatherings/manage/[id]/page.tsx
front/src/app/gatherings/manage/components/created/Card.tsx
front/src/app/gatherings/manage/components/created/List.tsx
front/src/components/NavBar.tsx

- 참여자 목록을 아코디언으로 보기/숨기기 기능 추가
- '관리하기'버튼 클릭 시 특정 아이디의 관리 페이지로 이동하도록 기능 추가

Feat: 아코디언 기능 구현 및 관리 페이지 연결

---

front/src/app/(auth)/components/LoginForm.test.tsx

- 로그인 성공 시 라우터 이동
-  API 호출 검증 테스트 추가

Feature: 로그인 MODULE MOCK 테스트 추가

---

front/src/app/layout.tsx
front/src/hooks/useModal.tsx

- 모달을 쉽게 사용할 있도록 useModal 훅 제작
- 모달 내부 요소 클릭 시 모달이 닫히는 문제 해결
- 특정 조건에서 tailwindCSS가 적용되지 않는 문제 해결
- useModal 훅에서 사용하는 모달 컴포넌트 추상화

Feat: useModal 훅 제작

---

front/next.config.mjs

- 시작페이지 라우팅 변경 '/' -> gathering
- public/image/navBar 폴더 추가

Feat: public 폴더구조 변경 & 시작페이지 리다이렉트

---

.github/workflows/deploy_to_EC2.yml

fix : EC2배포 YML파일의 front 프로젝트의 경로가 맞지않던점을 수정하였습니다.

fix : front 프로젝트의 경로가 맞지않던점을 수정하였습니다.

---

front/db.json
front/src/app/gatherings/manage/[id]/page.tsx
front/src/app/gatherings/manage/components/applied/Card.tsx
front/src/app/gatherings/manage/components/created/Card.tsx
front/src/app/gatherings/manage/components/manage/Tabs.tsx
front/src/app/gatherings/manage/page.tsx
front/tailwind.config.ts

Style: 드롭다운 레이아웃 수정

---

front/src/app/gatherings/[id]/detail/components/comments-section/CommentsSection.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatheringInfo.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/UserAvatar.tsx
front/src/app/gatherings/[id]/detail/page.tsx
front/src/app/gatherings/components/DateTag.tsx
front/src/app/gatherings/components/DeadLineTag.tsx
front/src/app/gatherings/components/ProgressBar.tsx

Rename: 모임상세 폴더구조 변경

---

front/src/app/gatherings/components/ConfirmBadge.tsx
front/src/app/gatherings/list/components/Card.tsx

- 카드 컴포넌트 UI 구현
- 개설확정 아이콘 잘림 현상 수정
- 모임 없는 경우 UI 추가
- react-query 사용해 gatherings fetch

Feat: 카드 컴포넌트 UI 구현

---

front/src/app/gatherings/[id]/detail/components/comments-section/CommentsSection.tsx
front/src/app/gatherings/[id]/detail/components/comments-section/Pagination.tsx

Design: Pagiantion 레이아웃 작업

---

front/src/apis/index.ts
front/src/libs/axiosInstance.ts
front/src/libs/gatherDetail.ts

Feat: react-query 환경변수화

---

front/package.json
front/src/app/components/Navbar.tsx
front/src/app/reviews/components/content/Card.tsx
front/src/app/reviews/components/section/Tabs.tsx
front/src/app/reviews/page.tsx
front/src/hooks/reviews/useReviews.ts
front/src/libs/reviews.ts
front/src/types/reviews.ts
front/yarn.lock

- 타입별 리뷰 목록 데이터 연동 (정렬 필터링 기능은 아직 미구현)
- Axios  요청으로 데이터 불러옴

Feat: 모든 리뷰 목록 데이터 연동 및 타입별 처리 구현

---

front/src/app/components/LoadingSpinner.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/UserAvatar.tsx
front/src/hooks/queries/gatherDetailQuery.ts
front/src/libs/gatherDetail.ts
front/src/types/gatherings.ts

Feat: Gathering Section API 연동

---

front/src/app/components/SessionProvider.tsx
front/src/app/layout.tsx

Nextauth의 작동을 위해 세션 컨텍스트를 제공해주는 프로바이더를 추가하였습니다.

Feat : 세션 프로바이더 추가

---

front/src/app/components/LoginAlertModal.tsx
front/src/app/gatherings/[id]/detail/components/comments-section/ActionBtnGroup.tsx
front/src/app/gatherings/[id]/detail/components/comments-section/CommentsSection.tsx
front/src/app/reviews/components/section/Tabs.tsx

Feat: LoginModal

---

front/src/app/components/HeartIcon.tsx
front/src/app/gatherings/[id]/detail/components/comments-section/CommentsCard.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatheringInfo.tsx
front/src/hooks/rendering/useGatherTItle.ts
front/tailwind.config.ts

- 점수에 따른 하트 렌더링 추가
- 에니메이션 구현
- 모임 상세 제목 hook 으로 렌더 (임시적용)
- Heart 렌더링 hook 으로 변경

Feat: Heart 추가

---

front/src/app/components/Navbar.tsx
front/src/stores/useAuthStore.ts

- 로그인 후 getUserProfile API 호출하여 유저 정보를 Zustand에 저장
- Zustand의 userInfo 상태를 사용해 네브바에서 프로필 이미지 및 유저 정보 표시

Feat: 로그인 상태에서 프로필 정보 전역 상태 관리 구현

---

front/src/app/components/Navbar.tsx
front/src/app/reviews/components/content/ProgressBar.tsx
front/src/stores/useAuthStore.ts

Style: Navbar 드롭다운 수정   

---

front/src/app/gatherings/[id]/detail/components/comments-section/ActionBtnGroup.tsx
front/src/hooks/queries/gatherDetailQuery.ts

Fix: query invalidate 수정

---

front/src/app/reviews/components/content/Card.tsx
front/src/app/reviews/components/content/ProgressBar.tsx
front/src/app/reviews/components/content/SortControls.tsx
front/src/app/reviews/components/section/Tabs.tsx
front/src/libs/reviews.ts
front/src/types/reviews.ts

- 드롭다운에서 날짜를 선택하여 해당 날짜에 작성된 리뷰만 필터링하여 조회 가능하도록 기능 구현
- SortControls 컴포넌트에 Calendar 컴포넌트를 추가하여 날짜 필터링 적용 
- 적용 버튼 클릭 시 필터가 활성화되며, 선택된 날짜를 기준으로 리뷰 필터링"

Feat: 리뷰 필터링 기능에 날짜 선택 구현

---

front/src/app/components/Navbar.tsx
front/src/app/layout.tsx

- 네브바 스크롤 시 상단에 고정되도록 구현
- 화면 크기에 따라 드롭다운 위치가 유동적으로 변경되도록 반응형 스타일 적용
- lg 사이즈 이상에서 드롭다운이 좌측에, 그 외에서는 우측에 정렬되도록 개선
- 네브바 Menu.Items에 z-index 추가
- 네브바 프로필 이미지 사이즈 고정

style: 네브바 스크롤 시 상단 고정 및 드롭다운 반응형 스타일 개선

---

front/src/app/components/Toast.tsx
front/src/app/gatherings/[id]/detail/components/comments-section/ActionBtnGroup.tsx
front/src/app/gatherings/[id]/detail/components/comments-section/CommentsSection.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/[id]/detail/page.tsx

Fix: 이미지 없을 경우 기본 이미지 처리

---

front/src/apis/profile.ts
front/src/app/mypage/components/ReviewModal.tsx
front/src/app/mypage/components/UserImage.tsx
front/src/app/mypage/components/manage/OnLoading.tsx
front/src/app/mypage/components/manage/created/CreatedGatherings.tsx
front/src/app/mypage/components/manage/joined/JoinedGatherings.tsx
front/src/app/mypage/components/manage/reviews/ReviewsWritable.tsx
front/src/app/mypage/components/manage/reviews/ReviewsWritten.tsx
front/src/app/mypage/components/userinfo/ModifyProfileBtn.tsx
front/src/app/mypage/components/userinfo/ModifyProfileModal.tsx
front/src/app/mypage/components/userinfo/UserInfo.tsx
front/src/app/mypage/page.tsx
front/src/libs/axiosInstance.ts

- 모임 리뷰 모달 디자인 완료
- 프로필 수정 모달 디자인 완료
- 사진 전송 안되는 문제 해결

Feat: 모달 디자인 작업 및 기타 버그 수정

---

front/src/app/mypage/components/userinfo/ModifyProfileModal.tsx

Fix: 이미지 변경하지 않을 경우, 오류가 발생하는 버그 수정

---

front/src/app/gatherings/list/components/Date.tsx
front/src/app/gatherings/list/components/Deadline.tsx
front/src/app/gatherings/list/components/card/CardHeader.tsx
front/src/app/gatherings/list/components/card/CardImage.tsx
front/src/hooks/queries/useGatheringsQuery.ts

- useEffect를 이용해 클라이언트에서 마운트된 경우에만 날짜 포맷팅 수행

Fix: 초기 렌더링 시 서버사이드에서 날짜 불일치 문제 해결

---

front/src/app/gatherings/[id]/detail/components/comments-section/ActionBtnGroup.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/[id]/detail/page.tsx

- 모임삭제 성공 시 메인으로 이동 로직추가
- 리뷰목록 SSR 구현

Fix: 모임삭제 로직 추가

---

front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/[id]/detail/components/gathering-section/UserAvatar.tsx
front/src/app/gatherings/components/DateTag.tsx
front/src/app/gatherings/components/DeadLineTag.tsx
front/src/app/gatherings/list/components/Deadline.tsx
front/src/hooks/queries/gatherDetailQuery.ts
front/src/libs/gatherDetail.ts

- 유저 아바타 호버 시 애니메이션
- 모임 참여한 유저목록 길이 값 parameter 추가
- SSR 적용

Feat: 유저 아바타 호버 시 애니메이션

---

front/src/apis/profile.ts
front/src/app/mypage/components/ReviewModalBtn.tsx
front/src/app/mypage/components/manage/joined/JoinedGatherings.tsx
front/src/app/mypage/components/manage/reviews/ReviewsWritable.tsx
front/src/app/mypage/components/manage/reviews/ReviewsWritten.tsx
front/src/app/mypage/components/userinfo/ModifyProfileModal.tsx
front/src/hooks/queries/mypage.ts

- 본인이 작성하지 않은 리뷰가 나타나는 문제 수정
- 모임 ID가 잘못 전달되는 문제 수정
- 모임 참여 취소 후에 바로 반영 안되는 문제 수정

Fix: 마이페이지 버그 수정

---

front/src/app/gatherings/[id]/detail/components/gathering-section/GatehringSection.tsx
front/src/app/gatherings/components/DateTag.tsx
front/src/app/gatherings/components/DeadLineTag.tsx
front/src/hooks/queries/gatherDetailQuery.ts

- DateTag & DeadLineTag useEffect 제거
- 참여자 데이터 query 수정
- SSR

Fix: DateTag & DeadLineTag useEffect 제거

---

front/src/libs/createGatheringApi.ts
front/src/libs/gatheringsApi.ts

- fetch시 기존 formatted 처리 삭제
- create시 UTC 형식으로 dateTime 데이터 전송 수정

Fix: 날짜 처리 오류 수정

---

front/src/app/gatherings/components/create/CreateGatheringModal.tsx
front/src/app/gatherings/components/create/TimeButton.tsx
front/src/app/gatherings/components/list/CreateButton.tsx
front/src/hooks/queries/useCreateGatheringQuery.ts
front/src/libs/createGatheringApi.ts

- 파일찾기 텍스트 줄바꿈 문제 수정
- 시간 선택 시 다른 필드의 유효성 검사 에러 발생 문제 해결
- 토스트 적용
- 로그인/회원가입 후 돌아왔을 때 모임 만들기 모달 자동 열리도록 처리

Fix: 모임 만들기 에러 수정

---

front/src/app/gatherings/[id]/detail/ClientGather.tsx
front/src/app/gatherings/[id]/detail/page.tsx
front/src/app/gatherings/components/detail/comments-section/CommentsSection.tsx
front/src/app/gatherings/components/detail/gathering-section/GatehringSection.tsx
front/src/app/gatherings/components/detail/gathering-section/GatheringInfo.tsx
front/src/app/gatherings/components/detail/gathering-section/GatheringSecSkeleton.tsx
front/src/hooks/queries/gatherDetailQuery.ts
front/src/libs/gatherDetail.ts

- 댓글리스트 SSR 적용
- 리뷰목록 이원화 (임시적용) 추후 기존 Query와 병합
- 안정성 테스트 진행
- 리뷰목록 기존 Query와 병합

Feat: 댓글리스트 SSR 적용

---

front/src/app/components/Calendar.tsx
front/src/app/gatherings/components/card/CardParticipants.tsx
front/src/app/gatherings/components/create/CreateGatheringModal.tsx
front/src/app/gatherings/components/create/Location.tsx
front/src/app/gatherings/components/create/config.ts
front/src/app/gatherings/components/filter/CustomDayPicker.tsx
front/src/app/gatherings/components/list/Gatherings.tsx
front/src/app/gatherings/components/list/Icons.tsx
front/src/app/gatherings/components/list/Tabs.tsx
front/src/app/gatherings/components/list/config.ts
front/src/types/gatherings.ts

- 캘린더 컴포넌트에서 모달 여부에 따른 텍스트, 배경색 적용
- getStyles 함수로 모달과 기본 상태에 따른 스타일 설정 추가
- 모임 인원 아이콘 색상 및 텍스트 색상 변경
- config 파일 추가 및 변수명 수정

Style: 모달 캘린더, 모임 인원 아이콘 변경 색상 적용

---

front/src/app/gatherings/[id]/detail/ClientGather.tsx
front/src/app/gatherings/[id]/detail/page.tsx
front/src/app/gatherings/components/detail/ActionBtnGroup.tsx
front/src/app/gatherings/components/detail/comments-section/CommentsSection.tsx
front/src/app/gatherings/components/detail/gathering-section/GatehringSection.tsx
front/src/app/gatherings/components/detail/gathering-section/GatheringInfo.tsx
front/src/hooks/queries/gatherDetailQuery.ts
front/src/libs/gatherDetail.ts
front/src/libs/reviews.ts
front/src/types/gatherings.ts

- 모임상세 날짜 수정 registerEnd로 
- pageId, gatherId type을 number로 변경

Fix: 모임상세 날짜 수정 및 pageId 타입

---

front/src/app/components/LoadingSpinner.tsx
front/src/app/gatherings/[id]/detail/ClientGather.tsx
front/src/app/gatherings/[id]/detail/page.tsx
front/src/app/gatherings/components/DeadLineTag.tsx
front/src/app/gatherings/components/ProgressBar.tsx
front/src/app/gatherings/components/detail/ActionBtnGroup.tsx
front/src/app/gatherings/components/detail/gathering-section/GatehringSection.tsx

Fix: Deadine 태그 누락된 로직 수정

---

front/src/app/gatherings/components/DateTag.tsx
front/src/app/gatherings/components/DeadLineTag.tsx
front/src/app/gatherings/components/card/CardParticipants.tsx
front/src/app/gatherings/components/card/index.tsx
front/src/libs/prefetchGatherings.ts
front/src/types/gatherings.ts

- DateTag, DeadLineTag suppreessHydraionWarning 삭제
- prefetchGatherings 받아온후 ko 시간대로 변환
- isExpired 마운팅된 경우 판단하도록 수정
- join now 기본값으로 수정

Fix: Server 데이터 시간 변환

---

front/src/app/gatherings/components/DeadLineTag.tsx

- new Date()로 mismatch 에러 출력
- suppressHydrarionWarning 추가해 해결

Fix: DeadlineTag suppress 추가

---

front/src/app/(auth)/components/FormField.tsx

##style : 포커스시 보더색상 변경
- 로그인 , 회원가입 폼에 포커스시 색상 변경되게 바꿧습니다.,

style : 포커스시 보더색상 변경

---

front/src/app/(auth)/utils/postSignup.ts

fix : instance사용

---

front/src/app/favorites/components/Favorites.tsx
front/src/app/gatherings/components/list/Gatherings.tsx
front/src/app/gatherings/components/list/InfiniteScroll.tsx
front/src/app/gatherings/components/list/Tabs.tsx

- 탭 애니메이션 에러 해결
- 찜한 페이지 데이터 fetch 에러 해결
- 무한스크롤 애니메이션 추가

Fix: 탭 애니메이션, 찜한 페이지 데이터 fetch 로딩 스피너 수정

---

front/src/app/favorites/page.tsx
front/src/app/gatherings/components/list/Gatherings.tsx
front/src/app/gatherings/components/list/InfiniteScroll.tsx

- 목록 페이지 깜빡임 없도록 초기값 1로 수정
- 목록, 찜한 목록 페이지 pb 추가

Fix: 목록 페이지 화면 깜빡임 해결

---

front/src/app/components/Navbar.tsx

Feat: 찜한 모임 개수 적용

---

front/src/app/gatherings/components/detail/gathering-section/GatehringSection.tsx
front/src/app/gatherings/components/detail/gathering-section/UserAvatar.tsx

Fix: 모집정원 수정

---

front/src/app/components/Gradient.tsx
front/src/app/favorites/components/Favorites.tsx
front/src/app/gatherings/components/card/CardImage.tsx
front/src/app/gatherings/components/card/index.tsx
front/src/app/gatherings/components/list/Gatherings.tsx
front/src/app/gatherings/components/list/InfiniteScroll.tsx
front/src/hooks/useScrollAnimation.ts

- 페이드 아웃 범위 조정
- 스크롤 되는 경우 Gradient 효과 나오도록 수정
- 훅 분리 및 Gradient 컴포넌트 분리
- 마감태그에 지정된 변수 변경

Fix: 애니메이션 및 마감일 오류 해결

---

front/src/app/favorites/components/Favorites.tsx
front/src/app/gatherings/components/DeadLineTag.tsx
front/src/app/gatherings/components/card/CardImage.tsx
front/src/app/gatherings/components/card/CardParticipants.tsx
front/src/app/gatherings/components/card/index.tsx
front/src/libs/prefetchGatherings.ts
front/src/types/gatherings.ts

- prefetchGatherings에서 미리 계산해 텍스트 추가로 보냄
- DeadLineTag props 추가 및 수정
- Card 변수명 수정

Fix: 서버 데드라인 에러 해결
